#### 코드로 방정식 표현하기

In [18]:
# numpy 없이 행렬 곱하기
coefficient_matrix = [[2,2,1], [2,-1,2], [1,-1,2]]
vector = [9,6,5]

result = []
for row in coefficient_matrix:
    list_k = []
    for i, j in zip(row,vector):
        k = i * j
        list_k.append(k)
    sum_k = sum(list_k)
    result += [sum_k]
    
print(f"행렬곱 결과 : {result}")

행렬곱 결과 : [35, 22, 13]


- 위와 같은 방식으로 행렬곱을 구하면 굉장히 큰 차원의 행렬에서는 속도 문제가 생김
- 파이썬은 인터프리터언어이기 때문에 속도가 느림
- 파이썬의 List는 만들어질때 메모리 공간을 가져옴
- 넘파이는 차례대로 데이터를 쌓는 형태를 가진다.

### Numpy(파이썬 과학 처리 패키지)

- Numerical Python
- 파이썬의 고성능 과학 계산용 패키지
- Matrix와 Vector와 같은 Array 연산의 표준
- 일반 List에 비해 빠르고 메모리 효율적임
- 반복문 없이 데이터 배열에 대한 처리를 지원함
- 선형대수와 관련된 다양한 기능을 제공함
- 인터페이스는 파이썬으로 되어있지만 내부적으로 돌아가는 구조는 C로 되었기에 C, C++, 포트란등의 언어와 통합 가능

참고
- cs231n
- scipy 공홈
- 데이터 사이언스 스쿨
- numpy 공홈
- 파이썬 라이브러리를 활용한 데이터 분석(책)

#### numpy의 가장 기본이 되는 단위(ndarray)

In [34]:
import numpy as np
test_array = np.array(["1",4,"5",7], np.float32) # numpy는 Dynamic Typing을 허용하지 않음, 사전에 메모리 공간을 정함
print(test_array)
print(type(test_array))
print(type(test_array[0])) # 하나의 원소(element)가 차지하는 메모리 공간이 64bit 까지이다.
print(test_array.shape) # 1-dimension : vector

[1. 4. 5. 7.]
<class 'numpy.ndarray'>
<class 'numpy.float32'>
(4,)


In [35]:
test_array = np.array([["1",4,"5",7]], np.float32)
print(test_array.dtype)
print(test_array.shape) # 튜플형태로 shape을 반환함, 2-dimsnsion : matrix

float32
(1, 4)


matrix의 형태를 따라가는 shape를 잘 파악해야 함
- shape: numpy array object의 dimension 구성을 반환함
- dtype: numpy array object의 데이터 타입(type, 자료형, 형)을 반환함

In [40]:
array_shape = np.array([[[1,2],[3,4]],[[5,6],[7,8]]]) # 3-dimension : tensor
array_shape.shape # 맨앞은 텐서의 깊이, col, row 순으로 의미함, 차원이 늘어날때마다 row는 뒤로 한칸씩 밀림

(2, 2, 2)

In [42]:
print(array_shape.ndim) # 텐서의 크기, 차원의 크기 출력
print(array_shape.size) # 전체 데이터의 개수를 int값으로 출력

3
8


numpy의 데이터 타입은 C 데이터 타입과 호환이 가능함 : float32, float64, int32, int64

#### handling shape

In [45]:
b = array_shape.reshape([2,4]) # array의 shape 크기를 바꿔주며 size만 같으면 맘대로 바꿀 수 있음
print(b)
print(b.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


가져오는 데이터가 vector인 경우 matrix로 바꿔주기 위해서 reshape함수를 사용하는 경우가 많음, 특히 sklearn을 사용하여 머신러닝 모델을 만드는 경우 입력값이 matrix로 들어가야 해서 많이 쓰임

In [49]:
b.reshape(-1,1) # 일반 vector array를 2-dimensional로 바구는 방법

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

#### flatten

- 다차원의 배열을 일차원의 vector로 쫙 펴주는 함수

In [54]:
print(array_shape)
print(array_shape.flatten())

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[1 2 3 4 5 6 7 8]


#### indexing & slicing

In [58]:
# indexing
a = np.array([[1,2,3],[4,5,6]],int)
print(a)
print(a[0,0]) # numpy indexing
print(a[0][0]) # list indexing

[[1 2 3]
 [4 5 6]]
1
1


In [59]:
a[0,0] = 12
print(a)

[[12  2  3]
 [ 4  5  6]]


In [66]:
# slicing
print(a[:,2:]) # 전체 행에 2열 이상
print(a[1,1:3]) # 1번째 행에 1~2열
print(a[0:2]) # 0~1 번째 행

[[3]
 [6]]
[5 6]
[[12  2  3]
 [ 4  5  6]]


슬라이싱 용법을 사용하여 for문을 사용하지 않고 바로 데이터를 가져와서 사용이 가능함

In [68]:
a[:,::2] # 2칸 씩 띄어서

array([[12,  3],
       [ 4,  6]])

#### arange

In [70]:
np.arange(30) # 범위를 지정하여 값의 list를 생성한느 명령어

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [71]:
np.arange(20).reshape(2,2,5)

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [73]:
np.arange(20).reshape(-1,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [76]:
np.arange(0, 10, 0.7) # 일반 python range는 float 단위로 나누지는 못함

array([0. , 0.7, 1.4, 2.1, 2.8, 3.5, 4.2, 4.9, 5.6, 6.3, 7. , 7.7, 8.4,
       9.1, 9.8])

#### ones, zeros

In [79]:
np.zeros(shape=(10,), dtype=np.int8)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [82]:
np.empty([3,5])

array([[0. , 0.7, 1.4, 2.1, 2.8],
       [3.5, 4.2, 4.9, 5.6, 6.3],
       [7. , 7.7, 8.4, 9.1, 9.8]])

In [84]:
test = np.arange(30).reshape(5,6)
np.ones_like(test) # test라는 변수의 같은 shape를 가지고 원소는 1로 채운 값 반환

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

#### identity(단위행렬)

In [85]:
np.identity(n=3, dtype=np.int8)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8)

In [86]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

#### eye

- 대각선이 1인 행렬로 k값의 시작 index의 변경이 가능함

In [89]:
np.eye(N=3, M=5, dtype=np.int8)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0]], dtype=int8)

In [91]:
np.eye(N=3, M=5, dtype=np.int8, k=2) # 대각선이 시작하는 위치값

array([[0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]], dtype=int8)

#### diag

- 대각 행렬의 값을 추출함

In [95]:
matrix = np.arange(9).reshape(3,3)
print(matrix)
print(np.diag(matrix))
print(np.diag(matrix, k=2)) # 대각선이 시작하는 위치값

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 4 8]
[2]


#### random sampling

- 데이터 분포에 따른 sampling으로 array를 생성

In [105]:
np.random.uniform(0,1,10).reshape(2,5) # 0~1사이의 균등분포를 이루는 값 10개를 반환

array([[0.21317769, 0.18266289, 0.41300679, 0.48895939, 0.66948375],
       [0.52480468, 0.21536651, 0.09633726, 0.82192343, 0.83996889]])

In [106]:
np.random.normal(0,1,10).reshape(2,5) # 0~1사이의 정규분포를 이루는 값 10개를 반환

array([[ 0.97096993, -0.09449965, -1.46452086,  0.62241614, -0.09339091],
       [-1.04057764,  0.43527668,  0.75002769,  1.64471723, -0.96215659]])

### axis(축)

- 모든 operation function을 실행할 떄, 기준이 되는 dimension 축
- 새로 생기는 부분이 axis가 0이 되고 기존 부분의 axis는 1씩 밀리게됨
- 축에 따라서 sum, min, max, sin, cos 계산이 가능함

#### concatenate

- numpy array를 합치는 함수
- vstack, hstack, concatenate

In [108]:
a = np.array([1,2,3])
b = np.array([4,5,6])
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [109]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

In [110]:
np.concatenate((a,b), axis=0)

array([1, 2, 3, 4, 5, 6])

In [113]:
a = np.array([[1,2], [3,4]])
b = np.array([[5,6]])
np.concatenate((a,b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

### array operation

In [115]:
test_a = np.arange(6).reshape(2,3)
test_a

array([[0, 1, 2],
       [3, 4, 5]])

In [116]:
test_a + test_a

array([[ 0,  2,  4],
       [ 6,  8, 10]])

In [117]:
test_a - test_a

array([[0, 0, 0],
       [0, 0, 0]])

In [123]:
# matrix 내 같은 위치의 원소끼리 연산 : element-wise operations
test_a * test_a

array([[ 0,  1,  4],
       [ 9, 16, 25]])

In [122]:
test_a.dot(test_a.T) # 행렬곱

array([[ 5, 14],
       [14, 50]])

In [125]:
test_a.T # 전치행렬

array([[0, 3],
       [1, 4],
       [2, 5]])

#### broadcasting

- shape이 다른 배열 간 연산을 지원하는 기능

In [127]:
matrix = np.arange(6).reshape(2,3)
scalar = 10
matrix + scalar

array([[10, 11, 12],
       [13, 14, 15]])

In [138]:
matrix1 = np.arange(1,10).reshape(3,3)
matrix2 = np.array([10,20,30])
print(matrix1.shape)
print(matrix2.shape)
matrix1 + matrix1

(3, 3)
(3,)


array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [140]:
matrix1 = np.arange(10)
matrix2 = np.array([10,20,30]).reshape(-1,1)
print(matrix1.shape)
print(matrix2.shape)
matrix1 + matrix2

(10,)
(3, 1)


array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

#### All & Any

In [141]:
a = np.arange(10)
np.any(a>5), np.any(a<0) # 조건에 맞는 원소가 하나라도 있으면 true

(True, False)

In [143]:
np.all(a>5), np.all(a<10) # 모든 원소가 조건에 맞으면 true

(False, True)

#### Comparison operation

- numpy는 배열의 크기가 동일 할 때, element간 비교의 결과를 boolean type으로 반환하여 돌려줌

In [154]:
test_a = np.array([1,3,0], float)
test_b = np.array([5,2,1], float)
test_a > test_b

array([False,  True, False])

In [155]:
(test_a > test_b).any()

True

In [157]:
a = np.array([1,3,0], float)
np.logical_and(a > 0, a < 3) # and 조건의 condition

array([ True, False, False])

In [159]:
b = np.array([True, True, False], bool)
np.logical_not(b) # not 조건의 conditionz

array([False, False,  True])

In [161]:
c = np.array([True, True, False], bool)
np.logical_or(b,c) # or 조건의 conditionz

array([ True,  True, False])

#### np.where

In [168]:
print(a)
np.where(a > 0, 3, 2) # 조건에 맞는 인덱스값을 반환해줌, True면 3 False면 2를 반환하도록

[1. 3. 0.]


array([3, 3, 2])

In [170]:
np.where(a>0) 

(array([0, 1], dtype=int64),)

In [172]:
a = np.array([1, np.NaN, np.Inf], float)
np.isnan(a) # Null값 반환

array([False,  True, False])

#### np.argmax

In [188]:
a = np.arange(10)
np.argmax(a) # 가장 큰 값의 인덱스값 반환

9

In [190]:
a = np.arange(10).reshape(2,5)
np.argmax(a[0], axis=0)

4

### boolean index

- numpy 배열은 특정 조건에 따른 값을 배열 형태로 추출 할 수 있음
- Comparison operation 함수들도 모두 사용가능

In [194]:
# 조건이 True인 index만 추출함
print(a)
print(a>5)
a[a>5]

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[False False False False False]
 [False  True  True  True  True]]


array([6, 7, 8, 9])

In [197]:
a = np.random.normal(0,5,100)
b = a > 3
b.astype(np.int) # 기존의 boolean 값을 int 자료형으로 바꿈으로써 조건에 맞으면 1 아니면 0으로 반환

array([1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0])

### fancy index

- numpy는 array를 index value로 사용해서 값을 추출하는 방법

In [199]:
a = np.array([2,4,6,8], float)
b = np.array([0,0,1,3,2,1], int) # 반드시 int로 선언
a[b] # bracket index, b 배열의 값을 index로 하여 a의 값들을 추출함

array([2., 2., 4., 8., 6., 4.])

In [202]:
a.take(b) # bracket index와 같은 효과

array([2., 2., 4., 8., 6., 4.])

In [204]:
# matrix 형태의 데이터도 가능
a = np.array([[1,4], [9,16]], float)
b = np.array([0,0,1,1,0], int)
c = np.array([0,1,1,1,1], int)
a[b,c] # b를 row index, c를 column index로 변환하여 표시함

array([ 1.,  4., 16., 16.,  4.])