### 벡터란?

- 벡터는 숫자를 원소로 가지는 리스트(list) 또는 배열(array)
- 열벡터와 행벡터가 있으며 일반적으로 행벡터로 표현함
- 벡터끼리 같은 모양(shape)를 가지면 덧셈, 뺄셈, 성분곱(Hadamard prduct, element-wise product)을 계산할 수 있음

In [4]:
import numpy as np
x = [1, 7, 2]
x = np.array([1, 7, 2]) # 행벡터

1차원의 공간(스칼라) - 1차원 1개의 축인 수직선 상에 놓인 숫자  
2차원의 공간(벡터) - 2차원 2개의 축으로 좌표공간 상에서의 한점  
3차원 이상의 공간(텐서) - 3차원 3개 이상의 축으로 공간 에서의 한점

- 벡터는 공간에서 한 점을 나타냅니다
- 벡터는 원점으로부터 상대적 위치를 표현함
- 벡터에 스칼라 곱을 해주면 길이만 변함
- 스칼라의 값이 1보다 크면 길이가 늘어나고 1보다 작으면 길이가 줄어듬
- 단, 스칼라의 값이 0보다 작으면 벡터의 방향이 반대방향으로 가게됨

In [15]:
x = np.array([1, 2, 3])
y = np.array([2, 4, 6])

In [16]:
x + y # 벡터의 덧셈 : 벡터의 덧셈은 다른 벡터로부터 상대적 위치 이동을 표현합니다.

array([3, 6, 9])

In [13]:
x - y # 벡터의 뺄셈

array([-1, -2, -3])

In [18]:
x * y # 성분곱

array([ 2,  8, 18])

#### 벡터의 노름

- 벡터의 노름(norm)은 한 점인 벡터로 부터 원점까지의 거리를 말합니다.
- L1, L2 노름 두가지 종류가 있습니다
- L1 노름 : 각 성분 변화량의 절대값을 모두 더함(맨하튼 거리 방식)
- L2 노름 : 피타고라스 정리를 이용한 유클리드 거리를 계산함

In [20]:
def l1_norm(x):
    x_norm = np.abs(x) # 절대값
    x_norm = np.sum(x) # 원소를 모두 더함
    return x_norm

def l2_norm(x):
    x_norm = np.abs(x) # 절대값
    x_norm = np.sum(x) # 원소를 모두 더함
    x_norm = np.sqrt(x) # 제곱근을 구함
    return x_norm

<img src="https://imgur.com/7Luk5pr.jpg">

위의 그림은 원점으로 부터 거리가 1인 지점을 그린 그림으로 노름의 종류에 따라서 그림과 같이 기하학적 성질이 달라지게 됨  

기계학습의 목적에 따라서 사용되는 노름의 종류가 달라짐  
   - L1 노름 : 로버스트 학습, 라쏘 회귀
   - L2 노름 : 라플라스 분산, 릿지 회귀

#### 두 벡터 사이의 거리

- 노름을 이용해 두 벡터 사이의 거리를 계산할 수 있음
- 두 벡터 사이의 거리를 계산할때는 벡터의 뺄셈이 이용됨
- 두 벡터 사이의 거리를 이용하여 각도를 계산할 수 있음(L2 노름에서만 가능,제 2코싸인 법칙 활용)
- 제2 코사인 법칙 : $cos\theta = \frac {\lvert{x}\rvert^2 + \lvert{y}\rvert^2 - \lvert{x-y}\rvert^2}{2\lvert{x}\rvert^2\lvert{y}\rvert^2}$ , $cos\theta = \frac {2<x,y>}{2\lvert{x}\rvert^2\lvert{y}\rvert^2}, <x,y> = \sum^{d}_{i}{x_iy_i}$
- 내적(inner product) : 두 벡터들의 연산에 성분곱을 취한다음에 성분곱을 취한 벡터들을 모두 더하는 연산

#### 내적 이해하기

<img src="https://imgur.com/c8Tu0Xx.jpg">

- 내적은 정사영(orthogonal projection)된 벡터의 길이와 관련이 있음
- 정사영된 길이는 코사인 법칙에 의해 원래 벡터의 길이 a에 $cos\theta$를 곱한 값과 동일함
- 내적은 정사영 길이를 벡터 b의 길이 $\lvert\lvert{b}\rvert\rvert$ 만큼 조정한 값임
- **내적은 두 벡터의 유사도(similarity)를 측정하는데 사용 가능함**